"""Initial migration for Source and Content models

Revision ID: 0c33cf66470c
Revises: 
Create Date: 2026-02-24 15:24:30.760849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c33cf66470c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='sourcestatus'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_external_source_id'), 'sources', ['external_source_id'], unique=True)
    op.create_table('contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_content_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FILTERED', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_external_content_id'), 'contents', ['external_content_id'], unique=True)
    op.create_index(op.f('ix_contents_published_at'), 'contents', ['published_at'], unique=False)
    op.create_index(op.f('ix_contents_source_id'), 'contents', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_source_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_published_at'), table_name='contents')
    op.drop_index(op.f('ix_contents_external_content_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_sources_external_source_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
